[phases.setup]
nixPkgs = [
  "nodejs_22",
  "python313",
  "python313Packages.pip"
]

[phases.install]
cmds = [
  "npm install",
  "pip3 install --break-system-packages -r requirements.txt"
]

[start]
cmd = "npm start"